# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.py'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import threading

from PyQt5 import QtWidgets
from PyQt5.QtCore import pyqtSignal, QThread
from PyQt5.QtGui import QIcon

from BlackTheme import Ui_MainWindow,XX



class MyWindow(QtWidgets.QMainWindow, Ui_MainWindow):
    def __init__(self):
        super(MyWindow, self).__init__()
        self.setupUi(self)
        self.setWindowIcon(QIcon('三角形.jpg'))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    #styleFile = 'D:/qsseditor/Load-QSS-master/Load-QSS-master/examples/Coffee/coffee.qss'
    # 换肤时进行全局修改，只需要修改不同的QSS文件即可
    #style = CommonHelper.readQss(styleFile)
    mainwindow = XX()
    #mainwindow.setStyleSheet(style)
    myshow = MyWindow()
    myshow.setupUi(mainwindow)
    mainwindow.show()
    sys.exit(app.exec_())
